#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/theme/default/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/theme/default/scripts/wallpaper

# echo "~/.config/hypr/themes/apatheia/wallpapers$wallpaper"
# swaybg -m fill -i "$HOME/.config/hypr/themes/apatheia/wallpapers/$wallpaper" &
