#! /bin/bash

#define icons for workspaces 1-9
# ic=(0     輸  " " " " )
# ic=(0 一 二 三 四 五 六 七 八 九 〇)

export isDual="$(hyprctl monitors | grep ID | awk '{print $4}' | grep -Eo '[0-9]' | wc -l)"

if [[ $isDual == "2" ]]; then
  notify-send "$isDual"
  ic=(0 1 2 3 4 5 1 2 3 4 5)
else
  ic=(0 1 2 3 4 5 6 7 8 9)
fi

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | awk '{print $3}'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==1{print $3}'); do 
  export f"$num"="$num"
  export fnum=f"$num"
  export mon=$(hyprctl monitors | grep -B 2 "\($num\)" | awk 'NR==1{print $2}')
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]] && [[ ${1:11} != "special" ]]; then #set focused workspace
  # notify-send "${1:11}"
  unset -v "$fnum" 
  num=${1:11}
  export f"$num"="$num"
  export fnum=f"$num"
  # notify-send "$fnum"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  # notify-send "${1:12}"
  unset -v "$fnum"
  string=${1:12}
  num=${string##*,}
  # notify-send f"$num"
  export mon=${string/,*/}
  # notify-send "$mon"
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  # notify-send "${1:0:13}"
  unset -v "$fnum"
  string=${1:15}
  num=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  export o"$num"="$num"
  export onum=o"$num"
  # notify-send "${onum}"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  unset -v o"$num"
fi
}
module() {
#output eww widget
if [[ $isDual == "2" ]]; then
  # notify-send "0$o22$f22" 
  wknames=(0 0$o1$f1 0$o2$f2 0$o3$f3 0$o4$f4 0$o5$f5 0$o21$f21 0$o22$f22 0$o23$f23 0$o24$f24 0$o25$f25)
  echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
    (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
    "$(for i in {1..10}; do if [[ $i == '6' ]]; then
      printf "(button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/apatheia/scripts/workspace ${i+1}\'\" :onrightclick \"hyprctl dispatch workspace ${i+1} && $HOME/.config/hypr/themes/apatheia/scripts/default_app\" :class \"ws-btn ${wknames[i]}\" \"${ic[i]}\")";
      continue
    fi 
    printf "(button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/apatheia/scripts/workspace $i\'\" :onrightclick \"hyprctl dispatch workspace $i && $HOME/.config/hypr/themes/apatheia/scripts/default_app\" :class \"ws-btn ${wknames[i]}\" \"${ic[i]}\")"; done) " \
      )\
      )"
else
  wknames=(0 0$o1$f1 0$o2$f2 0$o3$f3 0$o4$f4 0$o5$f5 0$o6$f6 0$o7$f7 0$o8$f8 0$o9$f9 0$o10$f10 )
  echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
    (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
    "$(for i in {1..10}; do printf "(button :onclick \"hyprctl dispatch exec \'~/.config/hypr/themes/apatheia/scripts/workspace $i\'\" :onrightclick \"hyprctl dispatch workspace $i && $HOME/.config/hypr/themes/apatheia/scripts/default_app\" :class \"ws-btn ${wknames[i]}\" \"${ic[i]}\")"; done) " \
    )\
    )"
fi
}


module

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
